### PR TITLE
Wrap angular app in express app

### PR DESCRIPTION
**Pull request by nicholasfagan**

### CODE REVIEW

**Review by Xiappi — APPROVED** [review]
Everything looks good to me, removed some old api files that got duplicated. Really glad that we don't need to separately host the api anymore

**Comment by Xiappi** [comment]
@nicholasfagan Went and double checked the login stuff, realized we cannot login anymore. Since you're going to be working on the login session token stuff we should wait for that to be implemented before we merge this branch

**Comment by nicholasfagan** [comment]
@Xiappi I think I can get back our old login functionality with only a little bit of effort, which would allow this to be merged before the new login logic is done

**Comment by nicholasfagan** [comment]
@Xiappi That should do it - works just as before for me now. Requires to set DB_SSH_USER and DB_SSH_PASSWORD as environment variables (using `SET var=value` for cmd or `export var=value` for bash 

We should probably set up a proper dev database so we aren't constantly messing with production data.

**Pull request merged**
